check for conflicting revision and resolve with the most recent version
fielded/angular-nav-data pull request #50
Opened 2016-12-15 09:09 UTC by freefony

closes #43

2016-12-22 14:35 UTC, tlvince requested changes
The logic seems straightforward enough, but I think we need some integration tests here to be confident it works as intended.

2016-12-22 14:35 UTC, tlvince commented on .idea/angular-nav-data.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Should you commit these IDE things?

2016-12-22 14:35 UTC, tlvince commented on src/locations/locations.service.js
> +import { default as utilService } from '../utils/utils.service'
You're only using `checkAndResolveConflicts` from `utilService`, so you can do:

```js
import { checkAndResolveConflicts } from '../utils/utils.service'
```

2016-12-22 14:35 UTC, tlvince commented on src/locations/locations.service.js
> +    this.localDB.changes({conflicts: true, onChange: utilService.checkAndResolveConflicts.bind(null, this.localDB)})
Did you try without `bind`?

```diff
- this.localDB.changes({conflicts: true, onChange: utilService.checkAndResolveConflicts.bind(null, this.localDB)})
+ this.localDB.changes({conflicts: true, onChange: change => utilService.checkAndResolveConflicts(change, this.localDB)})
```

2016-12-22 14:35 UTC, tlvince commented on src/utils/utils.service.js
> +        if (conflictingRev.updatedAt) {
Shouldn't `updateAt` be checked to see if it's newer than the currently chosen `preferredRevision`?

2016-12-22 14:35 UTC, tlvince commented on src/utils/utils.service.js
> +  serialiseDocWithConflicts (Doc, prop) {
Why uppercase `Doc`? It's not a constructor.

2016-12-22 14:35 UTC, tlvince commented on src/utils/utils.service.js
> +    Object.keys(Doc).map((prop) => {
Why iterate over all keys if you're only looking for `_conflicts`? Can't you do `if (Doc._conflicts) mainDoc._conflicts = Doc._conflicts`?

2016-12-22 14:35 UTC, tlvince commented on src/utils/utils.service.js
> +      let serializedRevisions = this.serialiseDocWithConflictsByProp(changedDoc, 'updatedAt')
So this sorts conflicts by `updateAt`?

2016-12-22 14:35 UTC, tlvince commented on src/utils/utils.service.js
> +        return a[prop] > b[prop]
This will always return `false` if `prop` (`updatedAt`) is `undefined`

2016-12-23 01:00 UTC, tlvince commented
@freefony I took the liberty of writing a (failing) integration test. Please could you check the assertion and confirm whether my understand aligns with yours.

Also note I fixed a bug in the locations service whereby you need to use the injected version of the utils service (4886f2d). If you agree with that change, you'll also need to apply it to the other services.

2016-12-23 09:23 UTC, freefony commented on src/utils/utils.service.js
> +        if (conflictingRev.updatedAt) {
the `if` checks that the `changedDoc` does not have `updatedAt` property so at this point `preferredRevision` does not have an `updatedAt` property so cannot be newer

2016-12-23 09:25 UTC, freefony commented on src/utils/utils.service.js
> +      let serializedRevisions = this.serialiseDocWithConflictsByProp(changedDoc, 'updatedAt')
Yes. also adds the main doc (couchdb's "winning" rev) so all are in an array and can be sorted

2016-12-23 10:56 UTC, tlvince commented
@freefony I've added restart replication support to locations service and made sure the local rev is at `2-`. However, so far it doesn't even look like the `onChange` handler is called.

2016-12-23 11:57 UTC, freefony commented on src/utils/utils.service.js
> +    Object.keys(Doc).map((prop) => {
Was trying to copy the doc without the `_conflicts` array property i fixed this in an update commit

2016-12-23 12:03 UTC, tlvince commented
@freefony I fixed the change handler invocation in 3053a8f. Note angular-pouchdb's API is slightly different here.

2016-12-23 12:05 UTC, tlvince commented
The test still fails on `Error: undefined is not a constructor (evaluating 'this.serialiseDocWithConfl
ictsByProp(changedDoc, 'updatedAt')')`

2016-12-23 12:17 UTC, tlvince commented
That's fixed, but this is still not working as we'd expect as the `_conflicts` property is indeed a list of revs, not a list of docs. Note we're using PouchDB 5.4.x, not 6.x which the PouchDB docs are based on (might've been a source of confusion).

2016-12-23 12:22 UTC, freefony commented
Ok. i ll do `db.get` on each doc then

2016-12-23 12:33 UTC, tlvince commented
OK, NB, you don't need to fetch all rev docs, you can use `open_revs: [<rev>] | 'all'` instead, e.g.:

```js
if (doc._conflicts.length) {
  db.get(doc._id, { open_revs: doc._conflicts })
  //=> [{}, {}, …]
}
```

2017-01-04 13:17 UTC, tlvince requested changes
~~The test is failing for me with `Expected '2-' to be '3-'.`.~~

Actually, hold on, CouchDB wasn't started.

2017-01-04 13:17 UTC, tlvince commented on test/locations.service.integration.js
> -  var url = window.__env__.COUCHDB_URL || 'http://localhost:5984'
Was this causing any issues? I added it for ease of testing locally (can just run `npm t`)

2017-01-04 13:30 UTC, tlvince commented on src/utils/utils.service.js
> +          pouchdb.remove(changedDoc._id, revision._rev)
Could you do this a `bulkDocs` perhaps?

2017-01-04 14:02 UTC, tlvince requested changes
The test is intermittently failing as `callOnReplicationComplete` occasionally resolves before `pouchdb.put(preferredRevision)`.

One way to solve this would be to add callback registration on the change handler similar to how's done for replication. That'd also be a good place to bubble any errors to.

2017-01-04 14:02 UTC, tlvince commented on src/utils/utils.service.js
> +          .catch(err => {
Probably we should bubble these up to the caller so it can respond accordingly.

2017-01-04 14:05 UTC, tlvince commented
@freefony I'm going to have look at this intermittent test.

2017-01-04 19:28 UTC, tlvince approved these changes

2017-01-04 19:29 UTC, tlvince commented
@freefony this lgtm now. Please have a run through a feel free to merge if it lgty 👍

2017-01-05 11:08 UTC, merged